export default [
	{
		category: 'History',
		type: 'multiple',
		difficulty: 'medium',
		question: 'During the Mongolian invasions of Japan, what were the Mongol boats mostly stopped by?',
		correct_answer: 'Typhoons',
		incorrect_answers: ['Tornados', 'Economic depression', 'Samurai'],
	},
	{
		category: 'Entertainment: Board Games',
		type: 'multiple',
		difficulty: 'easy',
		question: 'How many dice are used in the game of Yahtzee?',
		correct_answer: 'Five',
		incorrect_answers: ['Four', 'Six', 'Eight'],
	},
	{
		category: 'General Knowledge',
		type: 'multiple',
		difficulty: 'medium',
		question: 'What is a &quot;dakimakura&quot;?',
		correct_answer: 'A body pillow',
		incorrect_answers: [
			'A Chinese meal, essentially composed of fish',
			'A yoga posture',
			'A word used to describe two people who truly love each other',
		],
	},
	{
		category: 'Entertainment: Television',
		type: 'multiple',
		difficulty: 'medium',
		question: 'In Breaking Bad, the initials W.W. refer to which of the following?',
		correct_answer: 'Walter White',
		incorrect_answers: ['William Wolf', 'Willy Wonka', 'Wally Walrus'],
	},
	{
		category: 'Geography',
		type: 'multiple',
		difficulty: 'easy',
		question: 'What is the capital of the US State of New York?',
		correct_answer: 'Albany',
		incorrect_answers: ['Buffalo', 'New York', 'Rochester'],
	},
	{
		category: 'Entertainment: Video Games',
		type: 'multiple',
		difficulty: 'medium',
		question: 'In what year were screenshots added to Steam?',
		correct_answer: '2011',
		incorrect_answers: ['2010', '2008', '2009'],
	},
	{
		category: 'Entertainment: Music',
		type: 'multiple',
		difficulty: 'easy',
		question:
			'&quot;The Singing Cowboy&quot; Gene Autry is credited with the first recording for all but which classic Christmas jingle?',
		correct_answer: 'White Christmas',
		incorrect_answers: ['Frosty the Snowman', 'Rudolph the Red-Nosed Reindeer', 'Here Comes Santa Claus'],
	},
	{
		category: 'Entertainment: Video Games',
		type: 'multiple',
		difficulty: 'medium',
		question:
			'What is the perk that was introduced in the &quot;Call Of Duty: Zombies&quot; map, &quot;Mob Of The Dead&quot;?',
		correct_answer: 'Electric Cherry',
		incorrect_answers: ['Quick Revive', 'Vulture Aid', 'Tombstone'],
	},
	{
		category: 'Entertainment: Film',
		type: 'multiple',
		difficulty: 'medium',
		question:
			'What character in the Winnie the Pooh films was added by Disney and does not appear in the original books?',
		correct_answer: 'Gopher',
		incorrect_answers: ['Tigger', 'Heffalumps', 'Rabbit'],
	},
	{
		category: 'Entertainment: Film',
		type: 'multiple',
		difficulty: 'medium',
		question: 'Which Marvel superhero did Chris Evans play prior to his role as Captain America?',
		correct_answer: 'Human Torch',
		incorrect_answers: ['Cyclops', 'Iceman', 'Daredevil'],
	},
]
